### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by hyeonjun-2** [Basars/issues#1]
# Test Issue
### 앞으로 프로젝트 관리를 위한 Test Issue 
앞으로 프로젝트의 일정과 진행 과정 공유를 issue를 통해 진행할 예정입니다.  
간단한 check같은 경우에는 issue를 open한 후 모두의 comment가 달리게 되면 close하는 방향으로 진행하고자 합니다. 
본 Issue는 앞으로 프로젝트를 진행하기 위한 Test Issue 입니다. 

### 확인 후 `comment` 부탁드립니다.

**Comment by kdh93** [comment]
확인
