### ISSUE TITLE
데이터셋 검수 중 에러가 너무 많은 데이터셋 - 3100번 폴더

### ISSUE THREAD

**Issue by minhopark-github** [Basars/issues#38]
제가 담당한 데이터셋 3100번 폴더가

1. 폴리곤이 잘 있는 유의미한 종양 사진에는 노이즈가 끼어있다.
2. 노이즈가 제거된 적절한 종양 사진에는 폴리곤이 제거되어있다.

이 두 가지 이유로 유의미한 종양사진들이 많이 걸러지는 좀 특이한 데이터셋이라 이슈에 남깁니다.
관심 있으신 분들은 한번씩 보시고 담당한 데이터셋에서 이런 데이터셋 자주 보셨는지, 이런 환자 데이터는 어떻게 처리하는 게 나을지 코멘트 부탁드립니다. 너무 많이 유의미한 종양이 걸러지면 그냥 데이터셋을 빼야 하나 싶어서요

저는 일단 제가 맡은 데이터셋 전체 중 절반 넘게 하면서 제일 데이터 많이 날아간 데이터셋 폴더입니다

labels에 invalid로 하고 싶은데 어디서 고르는지 몰라서 찾아보다가 일단 submit합니다.

**Comment by minhopark-github** [comment]
3195번 폴더는 전부 노이즈가 남아있어서 날아갔습니다.
차라리 이런 경우면 한 폴더 데이터셋 다 날리는게 맘 편한데. 3100번 폴더는 좀 아리까리하네요

**Comment by OrigamiDream** [comment]
노이즈가 크게 남아 있는 영역은 conv 연산 시 값이 크게 반영되지만, 언급하신 이미지들은 대부분의 경우 연산시에 영향을 미치기에는 아주 작은 영역인 것으로 보입니다.
최종 데이터세트에서는 이미지를 회전하거나 스케일링하는 등의 증강 작업이 반영될 예정이기에 작은 영역에 대한 노이즈는 정상 범주에 포함시켜도 된다고 생각합니다.
저는 작업 시 저런 이미지를 발견했을 때 정상처리를 한 대신 특이사항을 기재했습니다.

추가로 병변작업 경험이 있는 @hyeonjun-2 님의 의견도 들어보는게 좋겠습니다.

**Comment by OrigamiDream** [comment]
**작은 영역에 대한 노이즈**:
<img width="91" alt="s2" src="https://user-images.githubusercontent.com/5837620/146137429-0a90f13c-c929-4c33-a1ec-bb806893227e.png">

**큰 영역에 대한 노이즈**:
<img width="94" alt="s1" src="https://user-images.githubusercontent.com/5837620/146137435-3692e11a-1c97-41cb-8b15-f129469f2c6b.png">

부가적인 설명을 하자면, 위와 같은 경우들 중 전자는 증강으로 쉽게 해결이 가능하고, 후자의 경우 증강으로도 영향을 미칠 가능성이 있어서 검수 작업을 함에 따라 후자의 경우를 발견 시 제외하도록 하는게 좋아 보입니다.

**Comment by minhopark-github** [comment]
확인했고 차후에 저 두 폴더는 재검수 하겠습니다

**Comment by hyeonjun-2** [comment]
@OrigamiDream  동영씨 의견에 동의 합니다. 차후 augmentation시 노이즈 때문에 모델에 큰 영향이 들어갈 것으로 보입니다. 그리고 폴리곤 데이터의 경우 다음과 같은 경우에만 제거 하는 것이 좋을 듯 합니다.   
1. 첫번째 영상
![image](https://user-images.githubusercontent.com/68496294/146149356-962792e5-4f30-46a2-984c-5cc3afbd9eaf.png)
학습에 전혀 필요없는 데이터입니다. 

1. 폴리곤 누락 
![image](https://user-images.githubusercontent.com/68496294/146149055-ce691e45-7e80-430c-92ce-f2a12f981f7b.png)
위 사진을 보면 오른쪽 위 전체도 종양으로 들어가는 것이 육안으로 확인 되지만 상당수가 빠져있는 것을 확인 할 수 있습니다. 이러한 경우에는 우선적으로 제거한 후 차후 processing을 통해 데이터를 수정하는 것이 좋아 보입니다.

2. 동일 이미지 다른 폴리곤
![image](https://user-images.githubusercontent.com/68496294/146149505-cc860dbd-e603-4368-a086-34a55d4bb7d4.png)
![image](https://user-images.githubusercontent.com/68496294/146149523-b9096e21-f599-48be-95ef-5d01878bbc60.png)
동일이미지 다른 폴리곤일 경우 두개의 이미지중 하나만 제거해 주시면 될 것 같습니다.

3. 종양과 폴리곤 위치가 맞지않음
![image](https://user-images.githubusercontent.com/68496294/146149786-2f243592-ae12-4a42-8cfb-2ebaf0bee987.png)
위 사진의 경우 육안으로도 종양이 파악되지만 폴리곤이 맞지 않습니다. 

4. 노이즈
![image](https://user-images.githubusercontent.com/68496294/146149907-fe5e793d-37c5-4f31-8217-a7e88920c912.png)
영상전체에 노이즈가 들어갑니다. 제거해주시기 바랍니다.

5.마스크 에러
![image](https://user-images.githubusercontent.com/68496294/146150117-badd0ffe-32e0-4c9e-9fc4-ca61a51dab93.png)
이미지 전체가 마스킹 된 경우 입니다. 이 부분도 제거해 주시기 바랍니다.

---
## 예외
폴리곤 데이터가 누락 된 경우
![image](https://user-images.githubusercontent.com/68496294/146150369-61995cd5-1ec0-4c61-8e71-a1022f93f55f.png)
위 그림 처럼 폴리곤 일부분이 누락된 경우가 있습니다. 
앞선 1번 사항이므로 제거를 하는 것이 맞지만 누락된 부분이 작다면 포함하고 진행해도 괜찮을 것 같습니다.
