### ISSUE TITLE
데이터 검수 기준점 정리

### ISSUE THREAD

**Issue by hyeonjun-2** [Basars/issues#39]
# 데이터 검수 과정에서 발생한 기준점 차이에 대한 정리입니다. 
## 검수시 제거할 사항
---
1. 첫번째 영상
![image](https://user-images.githubusercontent.com/68496294/146149356-962792e5-4f30-46a2-984c-5cc3afbd9eaf.png)
학습에 전혀 필요없는 데이터입니다. 

2. 폴리곤 누락 
![image](https://user-images.githubusercontent.com/68496294/146149055-ce691e45-7e80-430c-92ce-f2a12f981f7b.png)
위 사진을 보면 오른쪽 위 전체도 종양으로 들어가는 것이 육안으로 확인 되지만 상당수가 빠져있는 것을 확인 할 수 있습니다. 이러한 경우에는 우선적으로 제거한 후 차후 processing을 통해 데이터를 수정하는 것이 좋아 보입니다.

3. 동일 이미지 다른 폴리곤
![image](https://user-images.githubusercontent.com/68496294/146149505-cc860dbd-e603-4368-a086-34a55d4bb7d4.png)
![image](https://user-images.githubusercontent.com/68496294/146149523-b9096e21-f599-48be-95ef-5d01878bbc60.png)
동일이미지 다른 폴리곤일 경우 두개의 이미지중 하나만 제거해 주시면 될 것 같습니다.

4. 종양과 폴리곤 위치가 맞지않음
![image](https://user-images.githubusercontent.com/68496294/146149786-2f243592-ae12-4a42-8cfb-2ebaf0bee987.png)
위 사진의 경우 육안으로도 종양이 파악되지만 폴리곤이 맞지 않습니다. 

5. 노이즈
![image](https://user-images.githubusercontent.com/68496294/146149907-fe5e793d-37c5-4f31-8217-a7e88920c912.png)
영상전체에 노이즈가 들어갑니다. 제거해주시기 바랍니다.

6. 마스크 에러
![image](https://user-images.githubusercontent.com/68496294/146150117-badd0ffe-32e0-4c9e-9fc4-ca61a51dab93.png)
이미지 전체가 마스킹 된 경우 입니다. 이 부분도 제거해 주시기 바랍니다.

---
## 예외
1. 폴리곤 데이터가 누락 된 경우
![image](https://user-images.githubusercontent.com/68496294/146150369-61995cd5-1ec0-4c61-8e71-a1022f93f55f.png)
위 그림 처럼 폴리곤 일부분이 누락된 경우가 있습니다. 
앞선 1번 사항이므로 제거를 하는 것이 맞지만 누락된 부분이 작다면 포함하고 진행해도 괜찮을 것 같습니다.

_Originally posted by @hyeonjun-2 in https://github.com/Basars/issues/issues/38#issuecomment-994487516_

**Comment by hyeonjun-2** [comment]
폴리곤 누락의 경우 종양이 이미지 외각에 있을 경우 몇몇 좌표값이 누락된 것이라 생각 됩니다. 이러한 경우 추후 프로세싱을 통해 사용이 가능 할 것으로 생각 됩니다. 이를 고려해 검수 진행해 주시면 될 것 같습니다.

**Comment by OrigamiDream** [comment]
> 폴리곤 누락의 경우 종양이 이미지 외각에 있을 경우 몇몇 좌표값이 누락된 것이라 생각 됩니다. 이러한 경우 추후 프로세싱을 통해 사용이 가능 할 것으로 생각 됩니다. 이를 고려해 검수 진행해 주시면 될 것 같습니다.

부가적으로 이러한 경우 스프레드시트에서 문제여부 상관없이 특이사항을 반드시 기재하는 것이 좋아보입니다.
특이사항을 이용하여 이미지를 쉽게 특정할 수 있으니 추후 처리에 큰 도움이 될 것으로 보입니다.

**Comment by minhopark-github** [comment]
맞아요. 병변을 확신하기 어려운 경우도 다 특이사항으로 적는게 좋을거 같습니다.
어차피 개개인이 조금씩 판단이 다를수는 있고 그거는 감안하더라도 특이사항이 많이 적혀 있으면 재검수 시에 용이하니
특이사항에 힘쓰면 좋을 것 같습니다.
이상 유무 체크는 기준에 맞춰 나름대로 하면 될 것 같구요

**Comment by hyeonjun-2** [comment]
네 우선적으로 제거 후 옆에 특이사항을 기재하고 난 뒤 재검수를 하면 될 것 같습니다. 생각보다 폴리곤이 누락되어있는 데이터나 위치가 맞지 않는 데이터의 경우가 별로 없더군요.. 이 부분은 1차 검수가 끝나고 난 뒤 전체회의를 거쳐 2차검수를 진행하면 좋을 것 같습니다.

**Comment by minhopark-github** [comment]
그리고 저는 일단 1차 검수는 다 끝내버려서. 끝낸거는 어쩔 수 없고 다음에 다시 진행하거나 재검수가 필요한 데이터셋들에 대해서는 이 기준에 맞춰서 하겠습니다.

저는 누락은 가끔 있었던 거 같고 용종으로 추정되나 폴리곤 없음이 제일 많았어요
위치가 맞지 않음 이라는 카테고리는 아예 쓰지 않았구요.
고름처럼 생기거나 피부가 맛탱이가 가거나 뭐 그런 정도도 다 포함해야 하나 해서 좀 판단이 어려워서
그냥 어지간하면 Unet 판단을 믿고 특이사항 적는 식으로 진행했어요

**Comment by segae333** [comment]
제가 여태 본것들은 폴리곤 누락이나 마스크 에러가 대부분인것 같습니다. 하지만 현준님이 올려준 분류 기준점들을 보니 판단에 조금씩 수정해야 할 것들이 보이네요. 이미 한것들은 어쩔수 없고 남은 이미지 분류에 참고 하곘습니다.

**Comment by BlessW** [comment]
현준님이 기준점을 얘기해주시니 도움이 많이 됩니다.  지금 생각해보면 고민하다 몇개 지나간 것도 있었는데 좀 더 신경써보겠습니다.
