### ISSUE TITLE
용어에 혼란이 있어서 여쭙습니다 

### ISSUE THREAD

**Issue by segae333** [Basars/issues#40]
현준님이 올려주신 검수 기준표를 보면 폴리곤과 마스크가 같은 뜻으로 쓰이는것 같은데 맞나요 ? 저희끼리 대화하는 중에도 폴리곤과 마스크가 혼용되는 것 같아서 폴리곤과 마스크의 정확한 정의를 알고 싶습니다.

**Comment by OrigamiDream** [comment]
폴리곤은 레이블 데이터에 포함된 각 꼭짓점의 좌표 데이터를 의미하고,
마스크는 해당 폴리곤들을 조합하여 만든 바이너리 이미지 중 밝은 영역에 해당하는 부분을 의미합니다.

**Comment by segae333** [comment]
뭔가 비슷하면서도 다르네요
